/**
 * Legal Modal System - Professional Terms of Service Display
 * Displays comprehensive legal content in a clean, accessible modal interface
 */

console.log('[Legal] Script loading...');

// Terms of Service content - structured for better readability
const TERMS_OF_SERVICE = {
    title: "Terms of Service for INEXASLI Platform and AI Services",
    
    // Main disclaimer at the top
    disclaimer: `The Services utilize third-party AI providers for response generation. User input data is transmitted to these external services for processing. The Developer does not control, endorse, or assume responsibility for the outputs, accuracy, or privacy practices of these external AI systems. By using the Services, users acknowledge that their data is transmitted to third-party AI providers and is subject to those providers' terms, policies, and security measures, over which INEXASLI has no control.

*Disclaimer: This website and its Services (the INEXASLI platform and all associated AI-powered analysis tools) are designed solely as educational exploration tools for personal learning and professional consultation preparation. They are not intended to serve as professional advice of any kind—including but not limited to financial, legal, medical, nutritional, psychological, or therapeutic advice—or as substitutes for professional services. All content is generated by artificial intelligence and should be used as a starting point for research and discussion with qualified professionals, not for final decision-making. While we strive to provide helpful AI-generated insights, individual circumstances vary widely due to numerous factors that may not be fully accounted for by AI systems. AI can make mistakes, produce inaccurate information, or misinterpret data. For personalized guidance tailored to your unique situation, always consult a licensed professional in the relevant field. Users should not rely on these AI tools for decision-making or planning, and any use is at their own risk.*`,

    sections: [
        {
            title: "Introduction",
            content: `Note: This document outlines the terms of service for the use of the INEXASLI platform and all associated AI-powered analysis tools (referred to collectively as the "Services") provided by INEXASLI (hereinafter referred to as the "Developer"). By using any of these Services, you agree to be bound by these terms of service. The term "user" refers to you, the reader, when accessing any of the Services. If you do not agree with these terms, you must not use the Services.

Description: The Services include various AI-powered exploration tools designed to help users explore concepts, generate insights, and prepare questions for professional consultation across multiple domains including but not limited to nutrition, decision-making, personality analysis, research assistance, event planning, philosophy, and other areas of personal and professional interest. All AI-generated content is intended as exploratory material to inform your discussions with qualified professionals, not as definitive guidance for decision-making.

Privacy Policy Compliance:
- The Developer complies with the General Data Protection Regulation (GDPR) for users within the European Union and also adheres to the Personal Information Protection and Electronic Documents Act (PIPEDA) for users in Canada.`
        },
        
        {
            title: "Intellectual Property Rights",
            content: `**Ownership**
- All rights, title, and interest in and to the Services, including IncomeIQ™, Vacation Worksheet, their respective pages, website, software, source code, databases, functionalities, graphics, designs, trademarks, service marks, and all related content (collectively, the "IP Assets"), are and will remain the exclusive property of INEXASLI.
- Users are granted a limited, non-exclusive, non-transferable, revocable license to access and use the Services for their personal, non-commercial, educational purposes.

**User-Generated Content**
- Any content, data, text, or information you submit or upload to the Services ("User Content"), including vacation cost estimates from Vacation Worksheet, may be used by you solely for your personal, non-commercial use in connection with the educational objectives of the Services.
- By submitting User Content, you grant the Developer a non-exclusive, royalty-free, worldwide license to use, store, display, reproduce, modify, create derivative works, and distribute such User Content as necessary to provide the Services.

**Feedback**
- If you provide feedback or suggestions about the Services, you grant the Developer a perpetual, non-exclusive, and royalty-free license to use, modify, and incorporate your feedback into the Services without further compensation to you.
- However, you will still maintain any ownership rights you have in your pre-existing intellectual property.

**Restrictions**
- You may not reproduce, duplicate, copy, sell, trade, or exploit for any commercial purposes any portion of the Services or their IP Assets without express written permission by the Developer.
- This includes reverse engineering or attempting to extract the source code of the Services or any part thereof, except as permitted by applicable law.`
        },

        {
            title: "Services Purpose",
            content: `**AI-Powered Exploration Tools**
- The INEXASLI platform provides AI-powered analysis tools designed to help users explore concepts and generate insights across various domains including nutrition, decision-making, personality analysis, research, event planning, philosophy, and other areas of personal interest.
- These tools are educational exploration aids intended to help users formulate better questions and prepare for consultations with qualified professionals in relevant fields.
- Interactive Learning: Users engage with AI-generated insights by inputting personal data, receiving exploratory analysis, and using these insights as starting points for further research and professional consultation.
- Visualization and Analysis: The Services provide visual representations and analyses of user data, serving as educational aids to help users understand concepts and explore possibilities before consulting with professionals.

**Professional Consultation Preparation**
- The primary purpose of these tools is to help users explore topics and prepare informed questions for discussions with licensed professionals.
- All AI-generated insights should be viewed as conversation starters and research directions rather than definitive guidance.
- Users are encouraged to use these exploratory insights to enhance their consultations with qualified experts in relevant fields.

**Third-Party AI Integration**
- The Services utilize third-party artificial intelligence providers (including but not limited to XAI/Grok) to generate responses and analysis.
- User input data is transmitted to these external AI services for processing and response generation.
- The Developer does not control the AI models, training data, or response generation methods of these third-party providers.
- AI responses may vary in accuracy, relevance, and appropriateness based on the limitations and biases inherent in large language models and AI systems.

**No Professional Advice**
- The Services provide AI-generated exploratory insights and analysis based on user input, intended solely for educational purposes and professional consultation preparation. None of these Services provide professional advice, including but not limited to medical, nutritional, financial, legal, psychological, therapeutic, or business advice.
- AI Exploration Tool: All outputs, analyses, and insights generated by the Services are AI-produced content designed to help users explore concepts and formulate questions for professional consultation. They should be viewed as starting points for research and discussion with qualified professionals, not as authoritative guidance.
- Nutritional and Health-Related Content: Any nutrition analysis, calorie calculations, or health-related insights provided by the Services are educational explorations only. They are not medical advice, nutritional counseling, or health assessments. Users should consult with licensed healthcare providers, registered dietitians, or other qualified health professionals for personalized health and nutrition guidance.
- Decision-Making and Business Insights: Analysis related to decision-making, business planning, or financial considerations are exploratory tools only. They are not professional business consulting, financial planning, or investment advice. Users should consult with qualified business advisors, financial planners, or other relevant professionals for important decisions.
- Psychological and Personality Analysis: Any personality assessments, psychological insights, or similar analysis are for entertainment and educational exploration only. They are not psychological evaluations, therapy, or mental health assessments. Users should consult with licensed mental health professionals for psychological guidance.
- For Learning and Exploration: Use AI-generated results to understand concepts, explore possibilities, and prepare questions for professional consultations. Always seek independent advice from qualified professionals for specific decisions in any field.`
        },

        {
            title: "Data Security & Privacy",
            content: `**Client-Side and Server-Side Processing**
- Form input data is stored in your browser's localStorage for continuity, but is also transmitted to Cloudflare Workers and third-party AI providers for processing.
- Privacy-conscious device fingerprints are generated locally in your browser for rate limiting and abuse prevention purposes.
- Your data travels internationally through Cloudflare's network and third-party AI provider servers for response generation.
- We do not permanently store your data, but it is temporarily processed through these external services.

**Data Storage and Security**
- All data you enter is stored in your browser's localStorage, specific to each Service's page, and remains on your device in plain text.
- Data retention: Your data stays in localStorage until you clear it or for up to 365 days, whichever comes first.
- Security depends on your browser and system. localStorage is not encrypted by default.
- Payment data security is managed by our third-party payment provider, adhering to industry standards (e.g., PCI DSS).

**International Users**
- Since no data leaves your device for storage, local data protection laws (e.g., GDPR for European users) apply to your own management of the data.

**Reporting Concerns**
- For questions about data security, AI processing, third-party data handling, or privacy practices, contact us at support@inexasli.com`
        },

        {
            title: "Rate Limiting and Device Fingerprinting",
            content: `**Privacy-Conscious Usage Monitoring**
- To ensure fair usage and prevent abuse, the Services implement privacy-conscious rate limiting using device fingerprinting technology.
- A unique identifier is generated based on non-personal browser characteristics including screen resolution, timezone, browser type, and canvas rendering patterns.
- Device fingerprints are used solely for rate limiting, abuse prevention, and ensuring fair access to AI processing resources.
- Fingerprint data automatically expires after 24 hours, ensuring that usage tracking resets daily for privacy protection.

**Centralized Rate Limiting System**
- The Services utilize a centralized rate limiting system powered by Cloudflare Workers and KV storage to enforce fair usage limits across all AI modules.
- Different AI tools have different usage limits based on processing complexity and resource requirements.
- The system monitors for rapid successive requests and other patterns that may indicate abuse.`
        },

        {
            title: "User Responsibility",
            content: `**Accuracy of Information**
- You are responsible for providing accurate and complete information when using the Services.
- Inaccuracies or omissions may impact the calculations and results.
- Examples of errors include:
  - Duplicate Entries: Entering the same financial data in multiple places on IncomeIQ™.
  - Typographical Errors: Unintentional mistakes from hitting the wrong button.
  - Unit Errors: Attributing an amount to the incorrect field within the specified time frame in IncomeIQ™.
  - Transposition Errors: Unintentional errors where numbers or letters are swapped or reversed.
  - Inaccurate vacation expenses (e.g., travel or lodging costs) in Vacation Worksheet.
- Consult with financial professionals before making any financial decisions.

**Appropriate Use**
- You agree to use the Services for educational purposes only and in compliance with all applicable laws.
- The Services must not be used in a manner that violates laws, infringes on anyone's rights, or is offensive or harmful.
- Prohibited actions include attempting to reverse engineer the Services, transmitting malicious code, or collecting personal data inappropriately.

**Sensitive Data Warning**
- You are strongly advised against entering sensitive personal data into the Services, including health information, financial details, or any GDPR-protected data.
- Once data is processed by third-party AI systems, it becomes subject to those providers' privacy practices and security measures.`
        },

        {
            title: "Services Accuracy & AI Limitations",
            content: `**AI-Generated Content Disclaimers**
- The AI-generated insights, analyses, and outputs provided by the Services are based on large language models and artificial intelligence systems that have inherent limitations, biases, and potential for errors.
- AI systems can produce inaccurate information, misinterpret user input, generate plausible-sounding but incorrect responses (known as "hallucinations"), and may reflect biases present in their training data.
- The Developer aims to provide helpful AI-generated explorations, but these are simplified analyses for learning and exploration purposes only and may not reflect real-world complexities or your specific circumstances. Do not rely on them for important decisions.
- Users should verify all AI-generated insights independently and consult with qualified professionals in relevant fields before making decisions based on any content from the Services.

**Third-Party AI Dependencies**
- The accuracy and functionality of the Services depend on third-party AI providers whose systems, models, and capabilities may change without notice.

**Bugs and Errors in Calculations**
- The Developer strives to ensure the functionality of the Services, but bugs, errors, or inaccuracies in calculations, outputs, or generated content may occur due to software limitations or unforeseen issues.
- The Developer shall not be liable for any damages, losses, or claims arising from bugs or errors in the Services' calculations, outputs, including but not limited to financial losses, missed opportunities, or incorrect data interpretation.
- Users acknowledge that such errors are inherent risks of using software tools and agree to use the Services at their own risk, relying on professional advice for critical decisions.`
        },

        {
            title: "Limitation of Liability",
            content: `**AI-Generated Content Disclaimers**
- No AI system is entirely free from errors, biases, or inaccuracies, and AI-generated results should not be relied upon for actual decision-making without professional consultation.
- Users acknowledge that the Services provide AI-generated exploratory insights only, and any decisions made based on AI outputs are at their own discretion and risk.

**Liability Cap**
- The Developer's liability shall be limited to the greater of the amount paid by the user for the Services in the 6 months preceding the claim, or a nominal sum of $100.
- The Developer shall not be liable for any indirect, incidental, special, consequential, or punitive damages.

**Warranty Disclaimer**
- The Services are provided "AS IS" and "AS AVAILABLE", without warranty of any kind, express or implied.

**Downtime Disclaimer**
- The Services may experience downtime due to maintenance, updates, technical issues, or third-party provider outages.
- The Developer does not guarantee uninterrupted access and shall not be liable for damages arising from downtime.`
        },

        {
            title: "Indemnification",
            content: `**User Holds Developer Harmless**
- You agree to defend, indemnify, and hold harmless the Developer, its officers, directors, representatives, employees, and agents from any actions, claims, damages, losses, liabilities, costs, and expenses arising from your access to or use of the Services, or your violation of these Terms of Service.
- This includes but is not limited to claims arising from your use of AI-generated content, data you input into the Services, or decisions you make based on the Services' outputs.

**Third-Party Claims**
- You agree to indemnify the Developer against any third-party claims related to your use of the Services or any content you generate, share, or distribute using the Services.`
        },

        {
            title: "Force Majeure",
            content: `**Acts Beyond Control**
- The Developer shall not be liable for any failure or delay in the performance of its obligations hereunder, where such failure arises from any cause beyond its reasonable control, including acts of God, civil unrest, war, fire, flood, strikes, or failure of internet service providers.
- This includes but is not limited to third-party AI provider outages, Cloudflare service interruptions, or other infrastructure failures that may affect the Services' availability or functionality.

**Service Availability**
- Users acknowledge that online services dependent on third-party infrastructure may experience interruptions, and the Developer makes no guarantees regarding continuous availability of the Services.`
        },

        {
            title: "Refund Policy",
            content: `**General Policy**
- All payments for the Services are non-refundable except as outlined below.
- You may request a refund within 7 days of your initial payment if you have not used the Services.
- After this 7-day period, or if you have used the Services, no refunds will be issued, except as required by law.

**Refund Process**
- To request a refund, contact support@inexasli.com within the 7-day window.
- Refunds will be processed within 14 business days via the original payment method.

**Consumer Rights**
- This refund policy does not affect your statutory rights under applicable consumer protection laws.`
        },

        {
            title: "Governing Law & Dispute Resolution",
            content: `**Governing Law**
- These terms will be governed by and construed in accordance with the laws of British Columbia, Canada.
- Disputes will be resolved in the courts of British Columbia.

**Dispute Resolution**
- Any dispute shall be resolved through negotiation, consultation, mediation, and/or arbitration.
- The place of dispute resolution shall be British Columbia, Canada, and the language used shall be English.

**Changes to Terms**
- These Terms of Service may be updated from time to time.
- Continued use of the Services after any changes constitutes your acceptance of the new terms.`
        }
    ],

    acceptance: `By using the Services, participating in interviews, or by indicating your acceptance through an electronic means (e.g., clicking "I Agree", checking a box), you acknowledge that you have read, understood, and agree to be bound by these Terms of Service.

By using the Services, you confirm that you will not use them for financial planning or decision-making and understand their educational limitations.

You consent to the collection, use, storage, and disposal of your information as outlined in these terms.

You agree that your use of the Services is at your own risk, understanding the educational nature and limitations of liability as described herein.`
};

/**
 * Create and show the legal modal using unified modal system
 */
function createLegalModal() {
    console.log('[Legal] Creating Terms of Service modal');

    // Generate HTML content for all sections
    let sectionsHtml = '';
    
    // Add table of contents/index
    sectionsHtml += `
        <div style="margin-bottom: 12px; margin-top: 0px; padding: 8px 12px; background-color: rgba(45, 90, 61, 0.1); border: 1px solid rgba(45, 90, 61, 0.3); border-radius: 6px;">
            <h3 style="color: #2d5a3d; margin: 0 0 6px 0; font-size: 0.9em; font-family: 'Geist', sans-serif; text-align: center;">Table of Contents</h3>
            <div style="display: grid; gap: 2px;">
                ${TERMS_OF_SERVICE.sections.map((section, index) => `
                    <a href="#section-${index}" onclick="scrollToSection('section-${index}'); return false;" style="
                        color: #2d5a3d; 
                        text-decoration: none; 
                        padding: 4px 8px; 
                        border-radius: 3px; 
                        transition: background-color 0.2s ease;
                        font-size: 0.8em;
                        font-family: 'Inter', sans-serif;
                        display: block;
                        border: 1px solid transparent;
                        line-height: 1.2;
                    " onmouseover="this.style.backgroundColor='rgba(45, 90, 61, 0.1)'" onmouseout="this.style.backgroundColor='transparent'">
                        ${index + 1}. ${section.title}
                    </a>
                `).join('')}
            </div>
            <p style="margin: 4px 0 0 0; font-size: 0.7em; color: #666; text-align: center; font-style: italic;">
                Click any section above to jump directly to it
            </p>
        </div>
    `;
    
    // Add disclaimer at the top
    sectionsHtml += `
        <div style="margin-bottom: 10px; padding: 8px; background-color: rgba(255, 0, 0, 0.1); border: 1px solid rgba(255, 0, 0, 0.3); border-radius: 4px;">
            <p style="margin: 0; font-size: 0.85em; line-height: 1.3; color: #d32f2f; font-weight: 500;">${TERMS_OF_SERVICE.disclaimer}</p>
        </div>
    `;
    
    // Add all sections with anchors
    TERMS_OF_SERVICE.sections.forEach((section, index) => {
        sectionsHtml += `
            <div id="section-${index}" style="margin-bottom: 16px; scroll-margin-top: 20px;">
                <h3 style="color: #2d5a3d; margin: 0 0 8px 0; font-size: 1.1em; font-family: 'Geist', sans-serif;">${index + 1}. ${section.title}</h3>
                <div style="font-size: 0.95em; line-height: 1.5; color: #333; white-space: pre-line;">${section.content}</div>
            </div>
        `;
    });

    const htmlContent = `
        <div class="markdown-content" style="text-align: left; font-family: 'Inter', sans-serif; width: 100%; max-height: 70vh; overflow-y: auto;">
            <h2 style="color: #2d5a3d; margin-top: 0; margin-bottom: 0px; font-size: 1.2em; font-family: 'Geist', sans-serif; text-align: center; line-height: 1.2;">${TERMS_OF_SERVICE.title}</h2>
            ${sectionsHtml}
        </div>
    `;

    window.openCustomModal(htmlContent, {
        maxWidth: '480px',
        onOpen: function(modal, modalContent) {
            // Add scroll function to modal context
            window.scrollToSection = function(sectionId) {
                const section = modalContent.querySelector(`#${sectionId}`);
                if (section) {
                    section.scrollIntoView({ 
                        behavior: 'smooth', 
                        block: 'start' 
                    });
                }
            };
        }
    });
}

/**
 * Public API function to open legal modal
 */
function openLegalModal() {
    console.log('[Legal] Opening Terms of Service modal');
    return createLegalModal();
}

/**
 * Alternative function names for convenience
 */
function openTermsOfService() {
    return openLegalModal();
}

function showTermsOfService() {
    return openLegalModal();
}

function showLegal() {
    return openLegalModal();
}

// Expose functions globally
window.openLegalModal = openLegalModal;
window.openTermsOfService = openTermsOfService;
window.showTermsOfService = showTermsOfService;
window.showLegal = showLegal;

// Auto-create modal on page load if requested via URL parameter
document.addEventListener('DOMContentLoaded', function() {
    const urlParams = new URLSearchParams(window.location.search);
    if (urlParams.get('terms') === 'true' || urlParams.get('legal') === 'true') {
        setTimeout(() => {
            openLegalModal();
        }, 500);
    }
});

console.log('[Legal] Script loaded successfully - Functions available: openLegalModal(), openTermsOfService(), showTermsOfService(), showLegal()');
