/**
 * Legal Modal System - Professional Terms of Service Display
 * Displays comprehensive legal content in a clean, accessible modal interface
 */

console.log('[Legal] Script loading...');

// Terms of Service content - structured for better readability
const TERMS_OF_SERVICE = {
    title: "Terms of Service for InexasliIQ Platform and AI Services",
    
    // Main disclaimer at the top
    disclaimer: `The Services utilize third-party AI providers for response generation. User input data is transmitted to these external services for processing. The Developer does not control, endorse, or assume responsibility for the outputs, accuracy, or privacy practices of these external AI systems. By using the Services, users acknowledge that their data is transmitted to third-party AI providers and is subject to those providers' terms, policies, and security measures, over which INEXASLI has no control.

*Disclaimer: This website and its Services (the InexasliIQ platform and all associated AI-powered analysis tools) are designed solely as educational exploration tools for personal learning and professional consultation preparation. They are not intended to serve as professional advice of any kind—including but not limited to financial, legal, medical, nutritional, psychological, or therapeutic advice—or as substitutes for professional services. All content is generated by artificial intelligence and should be used as a starting point for research and discussion with qualified professionals, not for final decision-making. While we strive to provide helpful AI-generated insights, individual circumstances vary widely due to numerous factors that may not be fully accounted for by AI systems. AI can make mistakes, produce inaccurate information, or misinterpret data. For personalized guidance tailored to your unique situation, always consult a licensed professional in the relevant field. Users should not rely on these AI tools for decision-making or planning, and any use is at their own risk.*`,

    sections: [
        {
            title: "Introduction",
            content: `Note: This document outlines the terms of service for the use of the InexasliIQ platform and all associated AI-powered analysis tools (referred to collectively as the "Services") provided by INEXASLI (hereinafter referred to as the "Developer"). By using any of these Services, you agree to be bound by these terms of service. The term "user" refers to you, the reader, when accessing any of the Services. If you do not agree with these terms, you must not use the Services.

Description: The Services include various AI-powered exploration tools designed to help users explore concepts, generate insights, and prepare questions for professional consultation across multiple domains including but not limited to nutrition, decision-making, personality analysis, research assistance, social guidance, event planning, philosophy, and other areas of personal and professional interest. All AI-generated content is intended as exploratory material to inform your discussions with qualified professionals, not as definitive guidance for decision-making.

Privacy Policy Compliance:
- The Developer complies with the General Data Protection Regulation (GDPR) for users within the European Union and also adheres to the Personal Information Protection and Electronic Documents Act (PIPEDA) for users in Canada.`
        },
        
        {
            title: "Intellectual Property Rights",
            content: `**Ownership**
- All rights, title, and interest in and to the Services, including IncomeIQ™, Vacation Worksheet, Promptemplate™, their respective pages, website, software, source code, databases, functionalities, graphics, designs, trademarks, service marks, and all related content (collectively, the "IP Assets"), are and will remain the exclusive property of INEXASLI.
- Users are granted a limited, non-exclusive, non-transferable, revocable license to access and use the Services for their personal, non-commercial, educational purposes.

**User-Generated Content**
- Any content, data, text, or information you submit or upload to the Services ("User Content"), including vacation cost estimates from Vacation Worksheet and prompts from Promptemplate™, may be used by you solely for your personal, non-commercial use in connection with the educational objectives of the Services.
- By submitting User Content, you grant the Developer a non-exclusive, royalty-free, worldwide license to use, store, display, reproduce, modify, create derivative works, and distribute such User Content as necessary to provide the Services.

**Restrictions**
- You may not reproduce, duplicate, copy, sell, trade, or exploit for any commercial purposes any portion of the Services or their IP Assets without express written permission by the Developer.
- This includes reverse engineering or attempting to extract the source code of the Services or any part thereof, except as permitted by applicable law.`
        },

        {
            title: "Services Purpose",
            content: `**AI-Powered Exploration Tools**
- The InexasliIQ platform provides AI-powered analysis tools designed to help users explore concepts and generate insights across various domains including nutrition, decision-making, personality analysis, research, social interactions, event planning, philosophy, and other areas of personal interest.
- These tools are educational exploration aids intended to help users formulate better questions and prepare for consultations with qualified professionals in relevant fields.
- Interactive Learning: Users engage with AI-generated insights by inputting personal data, receiving exploratory analysis, and using these insights as starting points for further research and professional consultation.

**Professional Consultation Preparation**
- The primary purpose of these tools is to help users explore topics and prepare informed questions for discussions with licensed professionals.
- All AI-generated insights should be viewed as conversation starters and research directions rather than definitive guidance.

**Third-Party AI Integration**
- The Services utilize third-party artificial intelligence providers (including but not limited to XAI/Grok) to generate responses and analysis.
- User input data is transmitted to these external AI services for processing and response generation.
- The Developer does not control the AI models, training data, or response generation methods of these third-party providers.

**No Professional Advice**
- The Services provide AI-generated exploratory insights and analysis based on user input, intended solely for educational purposes and professional consultation preparation. None of these Services provide professional advice, including but not limited to medical, nutritional, financial, legal, psychological, therapeutic, or business advice.`
        },

        {
            title: "Data Security & Privacy",
            content: `**Client-Side and Server-Side Processing**
- Form input data is stored in your browser's localStorage for continuity, but is also transmitted to Cloudflare Workers and third-party AI providers for processing.
- Privacy-conscious device fingerprints are generated locally in your browser for rate limiting and abuse prevention purposes.
- Your data travels internationally through Cloudflare's network and third-party AI provider servers for response generation.
- We do not permanently store your data, but it is temporarily processed through these external services.

**Data Storage and Security**
- All data you enter is stored in your browser's localStorage, specific to each Service's page, and remains on your device in plain text.
- Data retention: Your data stays in localStorage until you clear it or for up to 365 days, whichever comes first.
- Security depends on your browser and system. localStorage is not encrypted by default.
- Payment data security is managed by our third-party payment provider, adhering to industry standards (e.g., PCI DSS).

**International Users**
- Since no data leaves your device for storage, local data protection laws (e.g., GDPR for European users) apply to your own management of the data.`
        },

        {
            title: "Rate Limiting and Device Fingerprinting",
            content: `**Privacy-Conscious Usage Monitoring**
- To ensure fair usage and prevent abuse, the Services implement privacy-conscious rate limiting using device fingerprinting technology.
- A unique identifier is generated based on non-personal browser characteristics including screen resolution, timezone, browser type, and canvas rendering patterns.
- Device fingerprints are used solely for rate limiting, abuse prevention, and ensuring fair access to AI processing resources.
- Fingerprint data automatically expires after 24 hours, ensuring that usage tracking resets daily for privacy protection.

**Centralized Rate Limiting System**
- The Services utilize a centralized rate limiting system powered by Cloudflare Workers and KV storage to enforce fair usage limits across all AI modules.
- Different AI tools have different usage limits based on processing complexity and resource requirements.
- The system monitors for rapid successive requests and other patterns that may indicate abuse.`
        },

        {
            title: "User Responsibility",
            content: `**Accuracy of Information**
- You are responsible for providing accurate and complete information when using the Services.
- Inaccuracies or omissions may impact the calculations and results.
- Consult with financial professionals before making any financial decisions.

**Appropriate Use**
- You agree to use the Services for educational purposes only and in compliance with all applicable laws.
- The Services must not be used in a manner that violates laws, infringes on anyone's rights, or is offensive or harmful.
- Prohibited actions include attempting to reverse engineer the Services, transmitting malicious code, or collecting personal data inappropriately.

**Sensitive Data Warning**
- You are strongly advised against entering sensitive personal data into the Services, including health information, financial details, or any GDPR-protected data.
- Once data is processed by third-party AI systems, it becomes subject to those providers' privacy practices and security measures.`
        },

        {
            title: "Limitation of Liability",
            content: `**AI-Generated Content Disclaimers**
- No AI system is entirely free from errors, biases, or inaccuracies, and AI-generated results should not be relied upon for actual decision-making without professional consultation.
- Users acknowledge that the Services provide AI-generated exploratory insights only, and any decisions made based on AI outputs are at their own discretion and risk.

**Liability Cap**
- The Developer's liability shall be limited to the greater of the amount paid by the user for the Services in the 6 months preceding the claim, or a nominal sum of $100.
- The Developer shall not be liable for any indirect, incidental, special, consequential, or punitive damages.

**Warranty Disclaimer**
- The Services are provided "AS IS" and "AS AVAILABLE", without warranty of any kind, express or implied.

**Downtime Disclaimer**
- The Services may experience downtime due to maintenance, updates, technical issues, or third-party provider outages.
- The Developer does not guarantee uninterrupted access and shall not be liable for damages arising from downtime.`
        },

        {
            title: "Refund Policy",
            content: `**General Policy**
- All payments for the Services are non-refundable except as outlined below.
- You may request a refund within 7 days of your initial payment if you have not used the Services.
- After this 7-day period, or if you have used the Services, no refunds will be issued, except as required by law.

**Refund Process**
- To request a refund, contact support@inexasli.com within the 7-day window.
- Refunds will be processed within 14 business days via the original payment method.

**Consumer Rights**
- This refund policy does not affect your statutory rights under applicable consumer protection laws.`
        },

        {
            title: "Governing Law & Dispute Resolution",
            content: `**Governing Law**
- These terms will be governed by and construed in accordance with the laws of British Columbia, Canada.
- Disputes will be resolved in the courts of British Columbia.

**Dispute Resolution**
- Any dispute shall be resolved through negotiation, consultation, mediation, and/or arbitration.
- The place of dispute resolution shall be British Columbia, Canada, and the language used shall be English.

**Changes to Terms**
- These Terms of Service may be updated from time to time.
- Continued use of the Services after any changes constitutes your acceptance of the new terms.`
        }
    ],

    acceptance: `By using the Services, participating in interviews, or by indicating your acceptance through an electronic means (e.g., clicking "I Agree", checking a box), you acknowledge that you have read, understood, and agree to be bound by these Terms of Service.

By using the Services, you confirm that you will not use them for financial planning or decision-making and understand their educational limitations.

You consent to the collection, use, storage, and disposal of your information as outlined in these terms.

You agree that your use of the Services is at your own risk, understanding the educational nature and limitations of liability as described herein.`
};

/**
 * Create and show the legal modal
 */
function createLegalModal() {
    // Remove existing modal if present
    const existingModal = document.getElementById('legal-modal-backdrop');
    if (existingModal) {
        existingModal.remove();
    }

    // Create modal backdrop
    const modalBackdrop = document.createElement('div');
    modalBackdrop.id = 'legal-modal-backdrop';
    modalBackdrop.style.cssText = `
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background-color: rgba(0, 0, 0, 0.7);
        backdrop-filter: blur(5px);
        -webkit-backdrop-filter: blur(5px);
        z-index: 10000;
        display: flex;
        align-items: center;
        justify-content: center;
        opacity: 0;
        transition: opacity 0.3s ease;
        padding: 20px;
        box-sizing: border-box;
    `;

    // Create modal container
    const modalContainer = document.createElement('div');
    modalContainer.style.cssText = `
        background: white;
        border-radius: 16px;
        width: 100%;
        max-width: 800px;
        max-height: 90vh;
        box-shadow: 0 20px 60px rgba(0, 0, 0, 0.3);
        display: flex;
        flex-direction: column;
        transform: scale(0.9) translateY(20px);
        transition: all 0.3s ease;
        font-family: "Inter", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
    `;

    // Create header
    const header = document.createElement('div');
    header.style.cssText = `
        padding: 24px 28px 16px;
        border-bottom: 1px solid #e5e7eb;
        display: flex;
        align-items: center;
        justify-content: space-between;
        flex-shrink: 0;
    `;

    const title = document.createElement('h2');
    title.textContent = 'Terms of Service';
    title.style.cssText = `
        margin: 0;
        font-size: 24px;
        font-weight: 700;
        color: #111827;
        line-height: 1.2;
    `;

    const closeButton = document.createElement('button');
    closeButton.innerHTML = '×';
    closeButton.style.cssText = `
        background: none;
        border: none;
        font-size: 28px;
        color: #6b7280;
        cursor: pointer;
        padding: 4px;
        line-height: 1;
        border-radius: 6px;
        transition: all 0.2s ease;
        width: 32px;
        height: 32px;
        display: flex;
        align-items: center;
        justify-content: center;
    `;

    closeButton.addEventListener('mouseenter', () => {
        closeButton.style.backgroundColor = '#f3f4f6';
        closeButton.style.color = '#374151';
    });

    closeButton.addEventListener('mouseleave', () => {
        closeButton.style.backgroundColor = 'transparent';
        closeButton.style.color = '#6b7280';
    });

    header.appendChild(title);
    header.appendChild(closeButton);

    // Create content area
    const content = document.createElement('div');
    content.style.cssText = `
        padding: 0 28px 28px;
        overflow-y: auto;
        flex: 1;
        line-height: 1.6;
        color: #374151;
    `;

    // Add main disclaimer
    const disclaimerDiv = document.createElement('div');
    disclaimerDiv.style.cssText = `
        background: #fef3c7;
        border: 1px solid #f59e0b;
        border-radius: 8px;
        padding: 16px;
        margin-bottom: 24px;
        font-size: 14px;
        line-height: 1.5;
    `;
    disclaimerDiv.innerHTML = `<strong>Important:</strong> ${TERMS_OF_SERVICE.disclaimer.replace(/\*/g, '')}`;

    content.appendChild(disclaimerDiv);

    // Add sections
    TERMS_OF_SERVICE.sections.forEach(section => {
        const sectionDiv = document.createElement('div');
        sectionDiv.style.cssText = `
            margin-bottom: 32px;
        `;

        const sectionTitle = document.createElement('h3');
        sectionTitle.textContent = section.title;
        sectionTitle.style.cssText = `
            font-size: 20px;
            font-weight: 600;
            color: #111827;
            margin: 0 0 16px 0;
            padding-bottom: 8px;
            border-bottom: 2px solid #e5e7eb;
        `;

        const sectionContent = document.createElement('div');
        sectionContent.style.cssText = `
            font-size: 15px;
            line-height: 1.7;
            white-space: pre-line;
        `;
        
        // Process markdown-style formatting
        let processedContent = section.content
            .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
            .replace(/\- (.*?)(?=\n|$)/g, '• $1');
        
        sectionContent.innerHTML = processedContent;

        sectionDiv.appendChild(sectionTitle);
        sectionDiv.appendChild(sectionContent);
        content.appendChild(sectionDiv);
    });

    // Add acceptance section
    const acceptanceDiv = document.createElement('div');
    acceptanceDiv.style.cssText = `
        background: #f0fdf4;
        border: 1px solid #10b981;
        border-radius: 8px;
        padding: 20px;
        margin-top: 24px;
        font-size: 15px;
        line-height: 1.6;
    `;
    acceptanceDiv.innerHTML = `<strong>Acceptance:</strong><br>${TERMS_OF_SERVICE.acceptance}`;

    content.appendChild(acceptanceDiv);

    // Create footer with contact info
    const footer = document.createElement('div');
    footer.style.cssText = `
        padding: 16px 28px;
        border-top: 1px solid #e5e7eb;
        background: #f9fafb;
        border-radius: 0 0 16px 16px;
        text-align: center;
        font-size: 14px;
        color: #6b7280;
        flex-shrink: 0;
    `;
    footer.innerHTML = `
        For questions or concerns about these terms, contact us at: 
        <a href="mailto:support@inexasli.com" style="color: #2563eb; text-decoration: none;">support@inexasli.com</a>
    `;

    // Assemble modal
    modalContainer.appendChild(header);
    modalContainer.appendChild(content);
    modalContainer.appendChild(footer);
    modalBackdrop.appendChild(modalContainer);

    // Add event listeners
    const closeModal = () => {
        modalBackdrop.style.opacity = '0';
        modalContainer.style.transform = 'scale(0.9) translateY(20px)';
        setTimeout(() => {
            if (modalBackdrop.parentNode) {
                modalBackdrop.remove();
            }
        }, 300);
    };

    closeButton.addEventListener('click', closeModal);
    modalBackdrop.addEventListener('click', (e) => {
        if (e.target === modalBackdrop) {
            closeModal();
        }
    });

    // Keyboard support
    const handleKeydown = (e) => {
        if (e.key === 'Escape') {
            closeModal();
            document.removeEventListener('keydown', handleKeydown);
        }
    };
    document.addEventListener('keydown', handleKeydown);

    // Add to DOM and animate in
    document.body.appendChild(modalBackdrop);
    
    // Force reflow
    modalBackdrop.offsetHeight;
    
    // Animate in
    modalBackdrop.style.opacity = '1';
    modalContainer.style.transform = 'scale(1) translateY(0)';

    // Focus management for accessibility
    closeButton.focus();

    return {
        modal: modalBackdrop,
        close: closeModal
    };
}

/**
 * Public API function to open legal modal
 */
function openLegalModal() {
    console.log('[Legal] Opening Terms of Service modal');
    return createLegalModal();
}

/**
 * Alternative function names for convenience
 */
function openTermsOfService() {
    return openLegalModal();
}

function showTermsOfService() {
    return openLegalModal();
}

function showLegal() {
    return openLegalModal();
}

// Expose functions globally
window.openLegalModal = openLegalModal;
window.openTermsOfService = openTermsOfService;
window.showTermsOfService = showTermsOfService;
window.showLegal = showLegal;

// Auto-create modal on page load if requested via URL parameter
document.addEventListener('DOMContentLoaded', function() {
    const urlParams = new URLSearchParams(window.location.search);
    if (urlParams.get('terms') === 'true' || urlParams.get('legal') === 'true') {
        setTimeout(() => {
            openLegalModal();
        }, 500);
    }
});

console.log('[Legal] Script loaded successfully - Functions available: openLegalModal(), openTermsOfService(), showTermsOfService(), showLegal()');
