/**
 * Legal Modal System - Professional Terms of Service Display
 * Displays comprehensive legal content in a clean, accessible modal interface
 */

console.log('[Legal] Script loading...');

// Terms of Service content - structured for better readability
const TERMS_OF_SERVICE = {
    title: "Terms of Service for INEXASLI Platform, AI Services, and Business Automation",
    
    // Main disclaimer at the top
    disclaimer: `INEXASLI is a technology company that facilitates user AI interactions for educational purposes only, generating outputs from engineered prompts to support learning, not providing financial, medical, or professional advice. The Services utilize third-party AI providers for response generation. User input data is transmitted to these external services for processing. INEXASLI does not control, endorse, or assume responsibility for the outputs, accuracy, or privacy practices of these external AI systems. By using the Services, users acknowledge that their data is transmitted to third-party AI providers and is subject to those providers' terms, policies, and security measures, over which INEXASLI has no control.

*Disclaimer: This website and its Services (the INEXASLI educational technology platform) are designed solely as educational AI interaction tools for personal learning and professional consultation preparation. INEXASLI provides prompt engineering and user interface technology to facilitate interactions with third-party artificial intelligence systems. We are not a financial, medical, legal, or professional services company. All content is generated by third-party artificial intelligence systems through our engineered prompts and should be used as a starting point for research and discussion with qualified professionals, not for final decision-making. While our technology aims to provide helpful AI-generated educational content, individual circumstances vary widely due to numerous factors that may not be fully accounted for by AI systems. AI can make mistakes, produce inaccurate information, or misinterpret data. For personalized guidance tailored to your unique situation, always consult a licensed professional in the relevant field. Users should not rely on AI-generated content for decision-making or planning, and any use is at their own risk.*`,

    sections: [
        {
            title: "Introduction",
            content: `Note: This document outlines the terms of service for the use of the INEXASLI educational technology platform and managed business automation services (referred to collectively as the "Services") provided by INEXASLI, a technology company (hereinafter referred to as the "Developer"). By using any of these Services, you agree to be bound by these terms of service. The term "user" refers to you, the reader or business client, when accessing any of the Services. If you do not agree with these terms, you must not use the Services.

Company Definition: INEXASLI is a technology company that provides both educational AI interaction tools and managed business automation services (such as automated social media posting). We are not a financial services company, healthcare provider, legal services firm, or professional advisory business. Our core business is developing user interface technology, engineered prompts, and automation tools that facilitate educational and business interactions with third-party artificial intelligence systems.

Description: The Services include educational technology interfaces for learning and exploration, as well as managed automation services for business clients. Businesses purchase access to managed services, not ownership of the technology or code. All AI-generated content originates from third-party providers through our engineered prompts and is intended as educational material or for business automation, not as definitive guidance for decision-making.

Privacy Policy Compliance:
- The Developer complies with the General Data Protection Regulation (GDPR) for users within the European Union and also adheres to the Personal Information Protection and Electronic Documents Act (PIPEDA) for users in Canada.`
        },
        {
            title: "Business Automation Services",
            content: `**Managed Automation for Businesses**
- INEXASLI offers managed automation services (such as automated social media posting) for business clients using proprietary AI technology.
- Businesses purchase access to these managed services, not ownership of the underlying technology or code.
- Businesses must comply with all applicable platform rules (e.g., social media terms) and provide accurate, lawful data for posting.
- INEXASLI is not responsible for third-party platform restrictions, outages, or account actions.
- Businesses are responsible for reviewing and approving automated posts. INEXASLI does not guarantee the accuracy, appropriateness, or compliance of AI-generated content.
- Clients should monitor outputs and report any issues immediately. INEXASLI is not liable for reputational, legal, or financial consequences resulting from AI-generated content.`
        },
        {
            title: "Intellectual Property",
            content: `- All rights, title, and interest in and to the Services, including the website, software, source code, databases, functionalities, graphics, designs, trademarks, service marks, and all related content (collectively, the "IP Assets"), are and will remain the exclusive property of INEXASLI.
- Users are granted a limited, non-exclusive, non-transferable, revocable license to access and use the Services for their personal, non-commercial, educational purposes, or for business automation only as a managed service provided by INEXASLI.

**User-Generated Content**
- Any content, data, text, or information you submit or upload to the Services ("User Content") may be used by you solely for your personal, non-commercial use in connection with the educational objectives of the Services, or for business automation as managed by INEXASLI.
- By submitting User Content, you grant the Developer a non-exclusive, royalty-free, worldwide license to use, store, display, reproduce, modify, create derivative works, and distribute such User Content as necessary to provide the Services.

**Feedback**
- If you provide feedback or suggestions about the Services, you grant the Developer a perpetual, non-exclusive, and royalty-free license to use, modify, and incorporate your feedback into the Services without further compensation to you.
- However, you will still maintain any ownership rights you have in your pre-existing intellectual property.

**Restrictions**
- Commercial/business use is permitted only through INEXASLI’s managed services; direct access, resale, or sublicensing of the technology is prohibited without express written permission by the Developer.
- This includes reverse engineering or attempting to extract the source code of the Services or any part thereof, except as permitted by applicable law.`
        },
        {
            title: "Services Purpose",
            content: `**Educational Technology Platform**
- INEXASLI provides educational technology interfaces that facilitate user interactions with third-party AI systems for learning and exploration across various domains.
- Our technology includes prompt engineering, user interface design, and data organization tools that help users structure their interactions with artificial intelligence systems.
- These are educational technology tools intended to help users formulate better questions and prepare for consultations with qualified professionals in relevant fields.
- Interactive Learning: Users engage with third-party AI-generated content by inputting personal data through our interfaces, receiving AI responses, and using these responses as starting points for further research and professional consultation.

**Prompt Engineering and Technology Services**
- The primary purpose of our technology is to help users organize their thoughts and data for more effective AI interactions.
- Our engineered prompts and user interfaces are designed to facilitate educational AI conversations, not to provide professional guidance.
- All content generation is performed by third-party AI providers; INEXASLI provides only the technological framework for interaction.

**Third-Party AI Integration**
- The Services utilize third-party artificial intelligence providers (including but not limited to XAI/Grok) to generate all responses and analysis.
- User input data is transmitted to these external AI services for processing and response generation through our technological interfaces.
- INEXASLI does not control the AI models, training data, or response generation methods of these third-party providers.
- AI responses may vary in accuracy, relevance, and appropriateness based on the limitations and biases inherent in large language models and AI systems.

**No Professional Advice or Services**
- INEXASLI provides educational technology services only. We do not provide professional advice, including but not limited to medical, nutritional, financial, legal, psychological, therapeutic, or business advice.
- Technology Interface Only: All outputs, analyses, and insights are generated by third-party AI systems through our technological interfaces. These should be viewed as starting points for research and discussion with qualified professionals, not as authoritative guidance from INEXASLI.
- Educational Content: Any responses received through our platform originate from third-party AI providers and are intended for educational exploration only. They are not professional assessments, advice, or recommendations from INEXASLI.
- For Learning and Exploration: Use AI-generated results to understand concepts, explore possibilities, and prepare questions for professional consultations. Always seek independent advice from qualified professionals for specific decisions in any field.`
        },
        {
            title: "Data Security & Privacy",
            content: `**Client-Side and Server-Side Processing**
- Form input data is stored in your browser's localStorage for continuity, but is also transmitted to Cloudflare Workers and third-party AI providers for processing.
- Privacy-conscious device fingerprints are generated locally in your browser for rate limiting and abuse prevention purposes.
- Your data travels internationally through Cloudflare's network and third-party AI provider servers for response generation.
- We do not permanently store your data, but it is temporarily processed through these external services.

**Data Storage and Security**
- All data you enter is stored in your browser's localStorage, specific to each Service's page, and remains on your device in plain text.
- Data retention: Your data stays in localStorage until you clear it or for up to 365 days, whichever comes first.
- Security depends on your browser and system. localStorage is not encrypted by default.
- Payment data security is managed by our third-party payment provider, adhering to industry standards (e.g., PCI DSS).

**Payment Data**
- When you make a payment (e.g., for premium subscriptions), your payment information is processed securely via a third-party payment provider (Stripe). We do not store your full payment details on our servers; only minimal transactional data (e.g., username, transaction ID) is retained as required for billing and support purposes, in compliance with applicable laws.

**International Users**
- Since no data leaves your device for storage, local data protection laws (e.g., GDPR for European users) apply to your own management of the data.

**Reporting Concerns**
- For questions about data security, AI processing, third-party data handling, or privacy practices, contact us at support@inexasli.com`
        },
        {
            title: "Rate Limiting and Device Fingerprinting",
            content: `**Privacy-Conscious Usage Monitoring**
- To ensure fair usage and prevent abuse, the Services implement privacy-conscious rate limiting using device fingerprinting technology.
- A unique identifier is generated based on non-personal browser characteristics including screen resolution, timezone, browser type, and canvas rendering patterns.
- Device fingerprints are used solely for rate limiting, abuse prevention, and ensuring fair access to AI processing resources.
- Fingerprint data automatically expires after 24 hours, ensuring that usage tracking resets daily for privacy protection.

**Centralized Rate Limiting System**
- The Services utilize a centralized rate limiting system powered by Cloudflare Workers and KV storage to enforce fair usage limits across all AI modules.
- Different AI tools have different usage limits based on processing complexity and resource requirements (e.g., 2 requests per minute for income analysis, 1 request per minute for personality analysis).
- The system monitors for rapid successive requests and other patterns that may indicate abuse.`
        },
        {
            title: "User Responsibility",
            content: `**Accuracy of Information**
- You are responsible for providing accurate and complete information when using our educational technology interfaces.
- Inaccuracies or omissions may impact the AI-generated responses and educational content.
- Examples of user input errors include:
  - Duplicate Entries: Entering the same data in multiple fields
  - Typographical Errors: Unintentional mistakes when inputting information
  - Unit Errors: Attributing values to incorrect fields or time frames
  - Transposition Errors: Unintentional errors where numbers or letters are swapped or reversed
  - Incomplete data affecting the quality of AI-generated educational content
- Remember that all outputs are educational only - consult with qualified professionals before making any important decisions.

**Appropriate Use**
- You agree to use the Services for educational purposes only and in compliance with all applicable laws.
- The Services must not be used in a manner that violates laws, infringes on anyone's rights, or is offensive or harmful.
- Prohibited actions include attempting to reverse engineer the Services, transmitting malicious code, or collecting personal data inappropriately.

**Sensitive Data Warning**
- You are strongly advised against entering sensitive personal data into the Services, including health information, financial details, or any GDPR-protected data.
- Once data is processed by third-party AI systems, it becomes subject to those providers' privacy practices and security measures.

**Confidentiality**
- If you receive any confidential or proprietary information from the Developer or through the Services, you agree to maintain confidentiality and not disclose it to any third party.

**Changes in Financial Situation**
- As a user, you acknowledge that your financial situation may change over time.
- It is your responsibility to update your information in the Services for accurate results.
- Failure to update may result in inaccurate calculations.`
        },
        {
            title: "Third-Party AI Content & Technology Limitations",
            content: `**Third-Party AI Content Disclaimers**
- All educational content provided through our Services is generated by third-party AI systems that have inherent limitations, biases, and potential for errors.
- Third-party AI systems can produce inaccurate information, misinterpret user input, generate plausible-sounding but incorrect responses (known as "hallucinations"), and may reflect biases present in their training data.
- INEXASLI provides only the technological framework for accessing these third-party AI systems. We do not create, validate, or endorse the content generated by these external AI providers.
- Users should verify all AI-generated educational content independently and consult with qualified professionals in relevant fields before making decisions based on any content received through our platform.

**Third-Party AI Dependencies**
- The functionality of our educational technology platform depends entirely on third-party AI providers whose systems, models, and capabilities may change without notice to INEXASLI.
- INEXASLI has no control over the accuracy, availability, or performance of these third-party AI systems.

**Technology Platform Limitations**
- INEXASLI strives to ensure the functionality of our technology platform, but bugs, errors, or technical issues may occur due to software limitations or unforeseen technical problems.
- INEXASLI shall not be liable for any damages, losses, or claims arising from technology platform issues, third-party AI errors, or any content generated through our Services.
- Users acknowledge that technology platforms and AI systems have inherent risks and agree to use our Services at their own risk, relying on professional advice for critical decisions.`
        },
        {
            title: "Limitation of Liability",
            content: `**Third-Party AI Content Disclaimers**
- No AI system is entirely free from errors, biases, or inaccuracies, and third-party AI-generated content should not be relied upon for actual decision-making without professional consultation.
- Users acknowledge that our technology platform facilitates access to third-party AI-generated educational content and business automation only, and any decisions made based on this content are at their own discretion and risk.

**Business Automation Liability**
- INEXASLI is not liable for business losses, missed posts, reputational harm, or third-party platform actions (including account suspension or removal) resulting from use of the business automation services.
- INEXASLI is not responsible for the content generated by third-party AI (e.g., XAI) and recommends that clients review and approve all automated posts.

**Technology Platform Liability Cap**
- The Developer's liability shall be limited to the greater of the amount paid by the user for the technology services in the 6 months preceding the claim, or a nominal sum of $100.
- The Developer shall not be liable for any indirect, incidental, special, consequential, or punitive damages.

**Warranty Disclaimer**
- The technology platform is provided "AS IS" and "AS AVAILABLE", without warranty of any kind, express or implied.

**Downtime Disclaimer**
- The technology platform may experience downtime due to maintenance, updates, technical issues, or third-party provider outages.
- The Developer does not guarantee uninterrupted access and shall not be liable for damages arising from platform downtime.`
        },
        {
            title: "Indemnification",
            content: `**User Holds Developer Harmless**
- You agree to defend, indemnify, and hold harmless the Developer, its officers, directors, representatives, employees, and agents from any actions, claims, damages, losses, liabilities, costs, and expenses arising from your access to or use of our technology platform, or your violation of these Terms of Service.
- This includes but is not limited to claims arising from your use of third-party AI-generated content accessed through our platform, data you input into our technology interfaces, or decisions you make based on third-party AI content.

**Third-Party Claims**
- You agree to indemnify the Developer against any third-party claims related to your use of our technology platform or any third-party AI content you access, save, share, or distribute through our platform.`
        },
        {
            title: "Force Majeure",
            content: `**Acts Beyond Control**
- The Developer shall not be liable for any failure or delay in the performance of its obligations hereunder, where such failure arises from any cause beyond its reasonable control, including acts of God, civil unrest, war, fire, flood, strikes, or failure of internet service providers.
- This includes but is not limited to third-party AI provider outages, Cloudflare service interruptions, or other infrastructure failures that may affect the Services' availability or functionality.

**Service Availability**
- Users acknowledge that online services dependent on third-party infrastructure may experience interruptions, and the Developer makes no guarantees regarding continuous availability of the Services.`
        },
        {
            title: "Refund Policy",
            content: `**General Policy**
- All payments for the Services are non-refundable except as outlined below.
- You may request a refund within 7 days of your initial payment if you have not used the Services.
- After this 7-day period, or if you have used the Services, no refunds will be issued, except as required by law.

**Refund Process**
- To request a refund, contact support@inexasli.com within the 7-day window.
- Refunds will be processed within 14 business days via the original payment method.

**Consumer Rights**
- This refund policy does not affect your statutory rights under applicable consumer protection laws.`
        },
        {
            title: "Privacy Policy",
            content: `**Information We Collect**
- Account information provided during OAuth authorization (username, profile data)
- Content you authorize us to post (text, images, scheduling preferences)
- Technical information (IP address, browser type, device identifiers for rate limiting)
- Usage analytics (features used, error logs, performance metrics)

**How We Use Your Information**
- To provide social media automation services as requested
- To authenticate with third-party platforms (X, Instagram) on your behalf
- To generate AI-powered content using third-party providers (XAI/Grok)
- To monitor service performance and prevent abuse through rate limiting
- To communicate with you about service updates or issues

**Information Sharing**
- **Third-Party AI Providers:** Content data is transmitted to XAI for AI generation
- **Social Media Platforms:** Authorized content is posted to X, Instagram per your instructions
- **Service Providers:** Cloudflare Workers for hosting, Stripe for payment processing
- **Legal Requirements:** When required by law or to protect our rights

**Data Retention and Security**
- OAuth tokens stored securely and can be revoked by you at any time
- Generated content temporarily processed, not permanently stored by us
- Industry-standard security measures including encrypted data transmission
- You can delete your account and associated data by contacting support

**Your Rights and Choices**
- Revoke social media platform access through their settings
- Request data deletion by contacting support@inexasli.com
- Opt out of AI content generation by discontinuing service use
- Update your preferences through our service interface

**Third-Party Privacy Practices**
- X/Twitter: Subject to X Privacy Policy and Developer Agreement
- Instagram/Meta: Subject to Meta Privacy Policy and Platform Terms
- XAI: Subject to XAI Privacy Policy for AI content generation
- We are not responsible for third-party privacy practices

**Contact Information**
- Email: support@inexasli.com
- We will respond to privacy inquiries within 30 days
- For data deletion requests, we will process within 30 days where technically feasible

**International Data Transfers**
- Data may be processed in United States, Canada, and other jurisdictions
- We comply with GDPR for EU users and PIPEDA for Canadian users
- Adequate safeguards in place for international transfers`
        },
        {
            title: "Social Media Platform Integration",
            content: `**General Integration Principles**
- All social media integrations use OAuth 2.0 authorization for secure access
- Users must explicitly authorize each platform connection and can revoke access at any time
- We comply with all applicable platform developer agreements and policies
- Automated posting is performed only with explicit user consent and within platform guidelines

**User Authorization and Consent**
- Clear disclosure of what content will be posted and where
- Explicit consent required before any automated posting actions
- Users shown preview of content before publication when possible
- Respect for user's platform settings (private accounts, blocking, etc.)

**Content and Data Handling**
- AI-generated content is created using third-party providers (XAI/Grok)
- Content is temporarily processed for posting, not stored long-term
- Users retain ownership of their original content and account data
- Platform-specific content requirements and restrictions are followed

**Rate Limiting and Usage**
- Automated actions performed within platform rate limits
- Fair usage policies prevent spam and abuse
- Graceful handling of platform outages or restrictions
- Users notified of any posting failures or limitations

**Platform-Specific Terms:**

**X/Twitter Integration**
- Full compliance with X Developer Agreement and Automation Rules
- Respect for X's rate limits and usage guidelines
- Proper attribution of X as content source when required
- Users must authorize posting actions and can revoke access via X settings
- Content must comply with X Rules and community guidelines
- No circumvention of X's spam detection or security measures

**Instagram/Meta Integration**
- Full compliance with Meta Platform Terms and Instagram API Terms
- Respect for Instagram's content policies and community guidelines
- Proper handling of Instagram business account requirements
- Users authorize through Instagram's OAuth flow with appropriate scopes
- Content published only to accounts user has authorized access to
- Compliance with Meta's data use policies and privacy requirements
- Support for Instagram's content review and moderation systems

**Service Limitations**
- Platform outages or restrictions may affect service availability
- Changes to platform APIs may require service modifications
- We are not liable for platform-specific restrictions or account actions
- Users responsible for compliance with platform terms of service

**Data Portability**
- Users can export their data by contacting support
- Platform connections can be managed through respective platform settings
- Content history available through platform's own data export tools`
        },
        {
            title: "Governing Law & Dispute Resolution",
            content: `**Governing Law**
- These terms will be governed by and construed in accordance with the laws of British Columbia, Canada.
- Disputes will be resolved in the courts of British Columbia.

**Dispute Resolution**
- Any dispute shall be resolved through negotiation, consultation, mediation, and/or arbitration.
- Costs associated with dispute resolution are your responsibility.
- The place of dispute resolution shall be British Columbia, Canada, and the language used shall be English.
- All parties agree to submit to the jurisdiction of the courts of British Columbia for any disputes that cannot be resolved through mediation or arbitration.

**Changes to Terms**
- These Terms of Service may be updated from time to time.
- Continued use of the Services after any changes constitutes your acceptance of the new terms.`
        }
    ],

    acceptance: `By using our technology platform or managed business automation services, or by indicating your acceptance through an electronic means (e.g., clicking "I Agree", checking a box), you acknowledge that you have read, understood, and agree to be bound by these Terms of Service.

By using our technology platform, you confirm that you understand INEXASLI provides data organization tools, basic calculations, prompt engineering, user interface technology, and managed automation services to facilitate educational and business interactions with third-party AI systems.

You consent to the collection, use, storage, and disposal of your information as outlined in these terms for the purpose of providing our technology services.

You agree that your use of our technology platform and business automation services is at your own risk, understanding that all analytical and automated content is generated by third-party AI systems and is for educational or business purposes only.`
};

/**
 * Create and show the legal modal using unified modal system
 */
function createLegalModal() {
    console.log('[Legal] Creating Terms of Service modal');

    // Generate HTML content for all sections
    let sectionsHtml = '';
    
    // Add table of contents/index
    sectionsHtml += `
        <div style="margin-bottom: 12px; margin-top: 0px; padding: 8px 12px; background-color: rgba(45, 90, 61, 0.1); border: 1px solid rgba(45, 90, 61, 0.3); border-radius: 6px;">
            <h3 style="color: #2d5a3d; margin: 0 0 6px 0; font-size: 0.9em; font-family: 'Geist', sans-serif; text-align: center;">Table of Contents</h3>
            <div style="display: grid; gap: 2px;">
                ${TERMS_OF_SERVICE.sections.map((section, index) => `
                    <a href="#section-${index}" onclick="scrollToSection('section-${index}'); return false;" style="
                        color: #2d5a3d; 
                        text-decoration: none; 
                        padding: 4px 8px; 
                        border-radius: 3px; 
                        transition: background-color 0.2s ease;
                        font-size: 0.8em;
                        font-family: 'Inter', sans-serif;
                        display: block;
                        border: 1px solid transparent;
                        line-height: 1.2;
                    " onmouseover="this.style.backgroundColor='rgba(45, 90, 61, 0.1)'" onmouseout="this.style.backgroundColor='transparent'">
                        ${index + 1}. ${section.title}
                    </a>
                `).join('')}
            </div>
            <p style="margin: 4px 0 0 0; font-size: 0.7em; color: #666; text-align: center; font-style: italic;">
                Click any section above to jump directly to it
            </p>
        </div>
    `;
    
    // Add disclaimer at the top
    sectionsHtml += `
        <div style="margin-bottom: 10px; padding: 8px; background-color: rgba(255, 0, 0, 0.1); border: 1px solid rgba(255, 0, 0, 0.3); border-radius: 4px;">
            <p style="margin: 0; font-size: 0.85em; line-height: 1.3; color: #d32f2f; font-weight: 500;">${TERMS_OF_SERVICE.disclaimer}</p>
        </div>
    `;
    
    // Add all sections with anchors
    TERMS_OF_SERVICE.sections.forEach((section, index) => {
        sectionsHtml += `
            <div id="section-${index}" style="margin-bottom: 16px; scroll-margin-top: 20px;">
                <h3 style="color: #2d5a3d; margin: 0 0 8px 0; font-size: 1.1em; font-family: 'Geist', sans-serif;">${index + 1}. ${section.title}</h3>
                <div style="font-size: 0.95em; line-height: 1.5; color: #333; white-space: pre-line;">${section.content}</div>
            </div>
        `;
    });

    const htmlContent = `
        <div class="markdown-content" style="text-align: left; font-family: 'Inter', sans-serif; width: 100%; max-height: 70vh; overflow-y: auto;">
            <h2 style="color: #2d5a3d; margin-top: 0; margin-bottom: 0px; font-size: 1.2em; font-family: 'Geist', sans-serif; text-align: center; line-height: 1.2;">${TERMS_OF_SERVICE.title}</h2>
            ${sectionsHtml}
        </div>
    `;

    window.openCustomModal(htmlContent, {
        maxWidth: '480px',
        onOpen: function(modal, modalContent) {
            // Add scroll function to modal context
            window.scrollToSection = function(sectionId) {
                const section = modalContent.querySelector(`#${sectionId}`);
                if (section) {
                    section.scrollIntoView({ 
                        behavior: 'smooth', 
                        block: 'start' 
                    });
                }
            };
        }
    });
}

/**
 * Public API function to open legal modal
 */
function openLegalModal() {
    console.log('[Legal] Opening Terms of Service modal');
    return createLegalModal();
}

/**
 * Alternative function names for convenience
 */
function openTermsOfService() {
    return openLegalModal();
}

function showTermsOfService() {
    return openLegalModal();
}

function showLegal() {
    return openLegalModal();
}

// Expose functions globally
window.openLegalModal = openLegalModal;
window.openTermsOfService = openTermsOfService;
window.showTermsOfService = showTermsOfService;
window.showLegal = showLegal;

// Auto-create modal on page load if requested via URL parameter
document.addEventListener('DOMContentLoaded', function() {
    const urlParams = new URLSearchParams(window.location.search);
    if (urlParams.get('terms') === 'true' || urlParams.get('legal') === 'true') {
        setTimeout(() => {
            openLegalModal();
        }, 500);
    }
});

console.log('[Legal] Script loaded successfully - Functions available: openLegalModal(), openTermsOfService(), showTermsOfService(), showLegal()');